User.create(name: 'user1', email: 'user1@email.com', password: 'password', is_estate: false)
User.create(name: 'user2', email: 'user2@email.com', password: 'password', is_estate: false)
User.create(name: 'user5', email: 'user5@email.com', password: 'password', is_estate: true)

City.create(name: '足立区')
City.create(name: '荒川区')
City.create(name: '板橋区')
City.create(name: '江戸川区')
City.create(name: '大田区')
City.create(name: '葛飾区')
City.create(name: '北区')
City.create(name: '江東区')
City.create(name: '品川区')
City.create(name: '渋谷区')
City.create(name: '新宿区')
City.create(name: '杉並区')
City.create(name: '墨田区')
City.create(name: '世田谷区')
City.create(name: '台東区')
City.create(name: '千代田区')
City.create(name: '中央区')
City.create(name: '豊島区')
City.create(name: '中野区')
City.create(name: '練馬区')
City.create(name: '文京区')
City.create(name: '港区')
City.create(name: '目黒区')

Choice.create(content: '閑静な住宅街')
Choice.create(content: '地域交流が活発')
Choice.create(content: '文化的活動が活発な地域')
Choice.create(content: '自然が豊か')
Choice.create(content: '大きな公園がある')
Choice.create(content: '繁華街に近い')
Choice.create(content: '商店街がある')
Choice.create(content: '子育てしやすい')
